#!/bin/bash
echo "The command name is: $0."
echo "# of args passed as parameters: $#."
echo "The value of the args: $1 $2 $3 $4 $5 $6 $7"
echo "Other way of showing: $@."
echo "Yet another: $*."
exit 0
