#!/bin/bash
if test $# -eq 0
  then 
    echo "Usage: $0 [name_of_file]"
    exit 1
fi
if test $# -gt 1
  then 
    echo "Usage: [name_of_file]"
fi
if test -f "$1"
  then 
    filename="$1"
    set `ls -il $filename`
    oname="$4"
    time="$9"
    echo -e "\nName\tOwnerName\tUpdateTime"
    echo -e "$filename\t$oname\t$time"
    exit 0
  else 
    echo "$0: argument must be an ordinary file"
    exit 1

fi
